### ISSUE TITLE
Help！New feature。

### ISSUE THREAD

**Issue by zgaxddnhh** [LanceMoe/openai-translator#1]
May I ask if you can add a feature to OpenAI Translator that allows it to be fixed on the desktop when using other software?

**Comment by LanceMoe** [comment]
Sorry, this is a PWA, it is difficult to do it on the table. However, I consider that it can be encapsulated into the Chrome extension for easy use. 😊

**Comment by zgaxddnhh** [comment]
Ok, Thank you for your response.
