### ISSUE TITLE
Release schedule inquiry

### ISSUE THREAD

**Issue by yingmanwumen** [LanceMoe/openai-translator#12]
Hi,

May I ask when the release is planned? 

Thanks!

**Comment by LanceMoe** [comment]
This is a real-time deployed web application (synchronized with the repository code), I don't think it needs to be "release".
If you only want to use it, just open this link directly:
https://translator.lance.moe/

**Comment by yingmanwumen** [comment]
> This is a real-time deployed web application (synchronized with the repository code), I don't think it needs to be "release". If you only want to use it, just open this link directly: https://translator.lance.moe/

Thanks a lot
