### ISSUE TITLE
请问可以部署到cloudflare pages上吗？

### ISSUE THREAD

**Issue by darkelfzdy** [LanceMoe/openai-translator#15]
请问可以部署到cloudflare pages上吗？

**Comment by darkelfzdy** [comment]
我仔细试了一下好像不行，只有部署到vercel上了

**Comment by LanceMoe** [comment]
这个项目本来就是部署在cf pages上的。

**Comment by darkelfzdy** [comment]
我试了好几次，在cf pages上都部署失败，请问部署命令是什么

**Comment by LanceMoe** [comment]
按这个设置：
![image](https://github.com/LanceMoe/openai-translator/assets/18505474/0bcd6307-34f8-46d1-bb37-919a981e0bc0)
![image](https://github.com/LanceMoe/openai-translator/assets/18505474/1b5ed33e-baa3-4c60-ada0-347add011257)

**Comment by darkelfzdy** [comment]
@LanceMoe 已成功部署到cf上，感谢
