### ISSUE TITLE
希望可以自定义prompt和添加原文和译文整体复制按钮

### ISSUE THREAD

**Issue by Joseph2Geek** [LanceMoe/openai-translator#19]
如题....谢谢大佬

**Comment by LanceMoe** [comment]
译文复制功能已经添加：https://github.com/LanceMoe/openai-translator/commit/373ca4446f2c3c7b2ed46d97cf053968f5e98e30

自定义prompt应该可以实现，我尝试添加一下。

**Comment by Joseph2Geek** [comment]
刚看到原来在历史记录里面，很棒，谢谢啦～
