### ISSUE TITLE
非常好软件！关于新功能

### ISSUE THREAD

**Issue by zenx0x** [LanceMoe/openai-translator#2]
能否增加快捷键，这将大大提高常用翻译软件人员的效率

**Comment by LanceMoe** [comment]
感谢您的反馈，需要什么样的快捷键功能呢。可否举几个例子。

**Comment by zenx0x** [comment]
deepL桌面端有个自定义的快捷键，在光标选定一段文字后使用快捷键，可弹出窗口然后自动把文字复制到翻译区翻译。

**Comment by LanceMoe** [comment]
这是一个 PWA 应用，所以没有这么高的权限。划词翻译这种需要封装成桌面的应用。
目前在考虑制作一个 Chrome 插件实现网页划词翻译。

**Comment by zenx0x** [comment]
我觉得很好用，虽然我主要搞通信的代码写的不多，以后有机会看看能不能完成这个工作。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年3月5日 15:53
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [LanceMoe/openai-translator] 非常好软件！关于新功能 (Issue #2)


这是一个 PWA 应用，所以没有这么高的权限。划词翻译这种需要封装成桌面的应用。
目前在考虑制作一个 Chrome 插件实现网页划词翻译。

―
