### ISSUE TITLE
Voice input, Line break, Erasing old text.

### ISSUE THREAD

**Issue by HarperLoop** [LanceMoe/openai-translator#20]
1. I encountered a problem with voice input. When I speak slowly, it quickly turns off. Could you please increase the speech waiting time or provide a manual on/off option for voice input so that the function doesn't turn off so quickly?

2. And also, the line break in the translated text is done letter by letter, which is not very convenient. Could you please make the line break for whole words if they don't fit in a single line?

3. It would be helpful to have a quick way to clear the original text field. After a translation is done, I need to manually select all the text to delete it and write new text. Could you add something like an "X" button in the top right corner to quickly delete the old text and enter new text?

**Comment by LanceMoe** [comment]
Thank you for your feedback, I think the three problems should be resolved now, please try to see if it works.

**Comment by HarperLoop** [comment]
This looks amazing, thank you so much)

сб, 8 июл. 2023 г., 23:08 Lance.Moe ***@***.***>:
