### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Quantatirsk** [LanceMoe/openai-translator#3]
Now translation results keep the same if you try several times. To adjust tempreture param, for example, from 1(default) to 1.5, will increase the diversity of translation results.

**Comment by LanceMoe** [comment]
Good suggestion, I plan to add the option of random tempreture param in the settings page.

**Comment by LanceMoe** [comment]
https://github.com/LanceMoe/openai-translator/commit/eeda9b35d7352496c17f92f26bfdc8c8602f7139

This feature has been implemented.
