### ISSUE TITLE
Translation Error Caused by Quotation Marks in Input Text

### ISSUE THREAD

**Issue by ZhangZhuoSJTU** [LanceMoe/openai-translator#6]
I understand it may seem nonsensical, but adding quotation marks to the sentence during translation could result in an inaccurate output. 

lol, largely for fun. But it would be better to fix it.

<img width="835" alt="image" src="https://user-images.githubusercontent.com/14835483/223012284-b7173a73-5f79-4621-a006-e1493ba32eb6.png">

**Comment by LanceMoe** [comment]
It's funny, and I actually found it at first too. 😆
At present, many applications based on OpenAI API may have this problem. Let me try to see how to solve it. 😊

**Comment by ZhangZhuoSJTU** [comment]
> It's funny, and I actually found it at first too. 😆 At present, many applications based on OpenAI API may have this problem. Let me try to see how to solve it. 😊

Lol, thanks for your reply. And yes! I believe it is somehow a fundamental issue for ChatGPT-based applications.
